### ISSUE TITLE
Unpausing the sim does not unpause recording

### ISSUE THREAD

**Issue by till213** [till213/SkyDolly#106]
**Describe the bug**
SkyDolly geht ja automatisch in die Pause, wenn man im SIM ins Menu geht (ESC). Und dann geht es automatisch auch wieder raus aus der Pause und nimmt weiter auf, wenn man das Menu wieder verlässt.

Bei der normalen SIM Pause (nicht Menu, sondern Standbild) geht SkyDolly zwar auch in die Aufnahme-Pause, aber kommt nicht mehr raus, wenn man im Sim die Pause beendet. Der Sim bleibt dann im Standbild und man muss SkyDolly manuell aus der Pause holfen, indem man z.b. wieder auf Aufnahme klickt. 

**To Reproduce**
- Start a flight (MSFS)
- Record the flight (Sky Dolly)
- Pause the flight (MSFS)
- Unpause the flight (MSFS)
- Bug: flight (and recording) is not resumed

**Expected behavior**
- Both flight and recording should be resumed

**Screenshots**
n/a

**Application version:**
 - Sky Dolly v0.16

**Comment by JackoKu** [comment]
Because I was concentrating on the problem yesterday, I forgot to tell you what an excellent program you have written.
To come up with the idea of not only making an mp4 recording, but to make the playback in the simulator directly and thus see any perspective afterwards is ingenious in itself.
I am currently in the process of working out the many possibilities of the program.
One more question:
Can I somehow also manage an export, e.g. to mp4, direect from the SkyDolly recording?
Because if I have to start the MSFS, SkyDolly and OBS (to record SkyDolly recordings) in order to create a nice movie afterwards, this is very hard on the performance of the PC, which means that there are stutter at least at the start of the scene.

About the problem yesterday.
After I restarted the PC and MSFS for certain reasons, the problem no longer occurred.
