### ISSUE TITLE
Sky Dolly window resizable

### ISSUE THREAD

**Issue by pmatei** [till213/SkyDolly#115]
When in formation mode, the Sky Dolly window isn't resizable. On my TV/resolution, the window is too big(height) and I cannot access ( I can't see) the bottom elements. They appear below my bottom margin of screen.
Please, can you do something?

**Comment by till213** [comment]
Not sure what you did in order to find a solution yourself so quickly - did you buy a bigger screen? ;)

But joking aside, I was just about to say that the Sky Dolly user interface (UI) should *always* be resizeable (when not in „minimal UI mode), regardless of which „module“ (e.g. „Formation“) is selected.

However there is always a *minimum* size for the UI, in order for all widgets (buttons, tables) to be visible. And that minimum size indeed depends on the selected module.

I am aware that especially the Formation module could use some additional „design love“: I consider especially the „relative position“ widget (well, collection of buttons really) merely a „placeholder“ for a proper widget. But the UI (apart from its functional aspect) has rather low priority for me currently, at least as far as „the looks“ is concerned. I always try to make it as usable as possible:

- Make it „self-explanatory“ (if possible)
- Provide keyboard shortcuts
- Try to reduce required „number of clicks“
- Etc.

That being said, I am also developing Sky Dolly on a MacBook Pro with 13“ display and a logical pixel size of 1280x800 (only). And the UI is perfectly accessible on that screen.

I am also testing - for the fun of it - on an old Netbook with an Intel Celeron 450 (1.8 GHz single core, IIRC - and 2 GB RAM) - for the „ultimative performance test“ ;)

And yes, the screen height is only 600 pixels, and the UI won‘t fit entirely (on Linux („window manager“) you can still move the „oversized“ window around though)


What screen size are we talking in your case? ;)

What you can do:

- Hide some UI elements in Sky Dolly
- Check your „scaling factor“ in your Windows screen settings (btw does the Sky Dolly UI appear „normally scaled“, especially compared to other Windows apps on your machine?)

**Comment by pmatei** [comment]
First of all, I want to thank you for the wonderful piece of software you have given us. I also appreciate that you have a good sense of humor. Thanks also for the very comprehensive reply. My solution(on Windows 11) was, as you assumed, the "scaling factor". It was set to 150%. Now I've set it to 100% and everything is fine.
