### ISSUE TITLE
Trembling flight plan map on MFD

### ISSUE THREAD

**Issue by JackoKu** [till213/SkyDolly#128]
Sky Dolly Version 0.16.3

**First of all, I would like to express how great Sky Dolly's functions are.**

I use the Cirrus SF50 VisionJet G2 aircraft from the MSStore.

A problem that does not make a good impression on playback:
The map that the flight plan is on keeps twitching back and forth during the whole playback.

Screenshots would not show the problem.
I could upload a video if needed but you should be able to reproduce it at any time.

**Comment by till213** [comment]
Hello,

"The map that the flight plan is on keeps twitching back and forth during the whole playback."

Which map exactly are we talking about? The overlay map of MSFS itself which is shown when you press (in my case) the V key - or some cockpit glass display map?

In any case, this is probably "out of control" for Sky Dolly: Sky Dolly merely records a specific set of simulation variables, most importantly the aircraft position and attitude, and it simply "plays back" those sampled data. It is then MSFS itself that places the aircraft at the desired location.

Any additional simulation is then simply calculated "on top" of this, but within MSFS itself. That includes visual effects such as smoke upon touchdown, audio effects, but also (to some degree) some instruments.

Specifically Sky Dolly does not record (replay) any "map specific data". So if any given map within MSFS is behaving weird then this is most likely not something I can fix myself.

**Comment by till213** [comment]
For the record: I just tested this with the in-game "VFR Map" (that appears as separate overlay window when pressing the default key V in MSFS) and the position of the aircraft was smooth: no "twitching back and forth" during replay.

**Comment by JackoKu** [comment]
Thank you for your detailed answer about the best replay programme I know.
Well, I wasn't talking about the VFR map of the MSFS, but about the Navigation Display (ND) in the aircraft itself, on which the flight plan is displayed.

**Comment by till213** [comment]
> Well, I wasn't talking about the VFR map of the MSFS, but about the Navigation Display (ND) in the aircraft itself

That‘s what I thought. I can only assume that this display has its own position calculation logic, and that the injected replay positions interfere with that aircraft custom logic.

So this would be something only the custom aircraft logic could solve (read: the third party aircraft manufacturer).

Note that Sky Dolly actually „freezes“ the aircraft position and physics calculations during replay (physic calculations that would otherwise „fight“ against the injected aircraft position and attitude).

Perhaps the aircraft logic (the third party) could take those „freeze“ settings into account? After all, the in-game VFR Map seems to work fine.
