### ISSUE TITLE
Is it not possible to switch to a slower aircraft during replay?

### ISSUE THREAD

**Issue by JackoKu** [till213/SkyDolly#129]
Sky Dolly Version 0.16.3

I use the Cirrus SF50 VisionJet G2 aircraft from the MSStore.

I have recorded flights with the Cirrus SF50 VisionJet G2 aircraft from the MSStore.
Now I wanted to play them back with a Cessna 172.
I read in the manual that when playing back the recorded flights, the aircraft that I have just loaded is used.
But apparently this is not so easy, as the speed is too high for the Cessna and the flight is therefore aborted very quickly (restart).
But I don't see anywhere the possibility to change this adaptation of the aircraft change by entering e.g. the speed.

Addendum:
Apparently this only works if I have previously started a flight or performed a teleportation and only then start a recorded flight.

**Comment by JackoKu** [comment]
Addendum:
Apparently this only works if I have previously started a flight or performed a teleportation and only then start a recorded flight.

**Comment by till213** [comment]
Hello,

Thank you for your question - and I am very sorry for the very late reply, let me first apologise for this!

Yes, the statement "the current aircraft" (technically: the "user aircraft") that is loaded is used for the replay.

Now the crucial thing to note here is that the exact same recorded flight data is used for replay, no matter what. This specifically also includes speed, as every recorded coordinate has an associated timestamp with it. And those timestamps do not change - at least not in the current version.

So you have recorded a flight with a fighter jet (e.g. the F/A-18) and am now replaying that flight with a Cessna 152? Well, there you go: the Cessna 152 will behave (at least "visually", during replay) like the previously recorded F/A-18, including the ability to accelerate like a jet and do barrel rolls like a jet.

"and the flight is therefore aborted very quickly (restart)"

This is probably because you did not _disable_ the simulation of engine/aircraft structure damage: it is highly recommended to disable all damage simulations within MSFS.

Note that also when you "seek" on the timeline (within Sky Dolly) back and forth the same "damage" could occur: most aircraft do not withstand the physical forces when being "teleported" from one airport right next to the other airport ;)

So again my recommendation (that applies to all replay software, in fact):

**-> Disable damage control (and also "crash detection") during replay**


That all being said, it would technically be possible to "slow down" (or accelerate) a flight path, by simply "scaling" the timestamps associated with each recorded data sample. Whether that would produce any meaningful results I don't know just yet, but I'll take a note of it in my own internal "feature wishlist" :)
