### ISSUE TITLE
IGC file format support (import / export)

### ISSUE THREAD

**Issue by scls19fr** [till213/SkyDolly#15]
**Is your feature request related to a problem? Please describe.**

Following discussion 

https://forums.flightsimulator.com/t/sky-dolly-v0-8-flightaware-kml-import-visualise-replay-real-world-flights/405367/12?u=scls19fr

IGC file format is widely used by glider pilots

**Describe the solution you'd like**

Supporting IGC both as import and export could be an important feature to have (especialy for glider pilots).

See Technical specification for GNSS flight recorders from international gliding commission (FAI)

https://www.fai.org/page/igc-free-software
https://www.fai.org/sites/default/files/igc_fr_specification_2020-11-25_with_al6.pdf

**Comment by till213** [comment]
Note to myself: the most important data (position, altitude, possibly timestamp) are in the so-called „B records“.

**Comment by scls19fr** [comment]
Some IGC parser implementations using several differents languages exist

https://github.com/topics/igc

C++ implementations can be found using

https://github.com/topics/igc?l=c%2B%2B

be aware that some implementations are released under GPL (so it could be a problem if you want to keep MIT license)... but I'm pretty sure you will find a simple manner of implementing B records parsing.

**Comment by scls19fr** [comment]
B records provide time (not date) so for full knowledge of timestamp (ie date and time) you need to also parse HFDTEddmmyy record (H=header)

I have never flown during night (above 00:00) but I think it's important to ensure timestamp are always increasing (if time is not increasing it's because that's a point which should be attached to another day).

**Comment by till213** [comment]
I am not promising any timeline here, but...

https://github.com/till213/SkyDolly/tree/feature-igc

(feature branch with initial import plugin just created).

By the way, is there really a need for an _export_ plugin? What would be the use case here? You can already visualise flight paths exported in KML format (with Google Earth and others)?

**Comment by scls19fr** [comment]
Having built in IGC import will be very convenient.
Maybe you are right @till213 maybe export to IGC is not necessary as KML export exist and some tools can convert KML files to IGC... But it simplifies creation of such IGC file without the need of an other tools.

**Comment by till213** [comment]
Jesus Christ! Already parsing the date of the flight becomes an adventure alone (note to myself):

* First, the [official documenation](https://www.fai.org/sites/default/files/igc_fr_specification_2020-11-25_with_al6.pdf), page 26, is pretty simple and clear: H F DTE **DATE:** DD MM YY, NN - or in other words: "The header H contains the date DTE, typically written by the flight recorder (F), spelled out again as "DATE:" and then the date is in the format DDMMYY, followed by an optional comma (,) and "flight number of the day" (NN)
* But another "[real world IGC](https://xp-soaring.github.io/igc_file_format/sample_igc_file.txt)" file already deviates from this, and we simply have: HFDTE250809 - so no **DATE:** string present!
* And the best of all: the example given in the [official documentation](https://www.fai.org/sites/default/files/igc_fr_specification_2020-11-25_with_al6.pdf), page 41, contradicts the formal specification as well: HF DTE DATE: 16 08 19 02 - so a flight on the 16th August 2019, but where is the comma to separate the flight number 02?

Oh, the joy of verbose text formats ;)

**Comment by till213** [comment]
A basic IGC import plugin has been implemented and downbranched into the current release v0.8.6 (see "Releases").

- Basic header data (H record) import (pilot name, glider type and ID)
- Basic task (C record) import (-> imported as waypoints in Sky Dolly, also see "Flight" dialog, key F)
- Basic position data import (B records)

Current limitations & known issues

- The GNSS (altitude above WGS84 elipsoid) is currently imported ("hardcoded"). I also tried with the provided "pressure altitude", but in most cases the imported flight path is either under or over the terrain data in MSFS
  * This might be amended with a future "altitude offset" setting in Sky Dolly
- Most IGC data records the glider "sitting on the ground" for a while - due to slight GPS "signal noise" the position changes ever so slightly - and with it the (reconstructed) heading - so the glider may "turn wildly" on the ground
  * This might be amended by taking the first "real movement vector" (which exceeds some distance threshold) into account in the future
- Depending on the sample rate of the IGC flight recorder (I have a file with a sample interval of 10 seconds only) it might simply not possible to reconstruct "tight turns" (e.g. when climbing in a "thermal layer" (?)): the aircraft in MSFS will then "wildly turn" (there is then simply no way - way too few data points - to properly reconstruct the attitude of the aircraft)
- Only "mandatory" B record (fix) data is imported, but e.g. currently not yet the (optional) "noise level"
  * This might be used in the future to turn off/on the aircraft engine, based on some "noise threshold level"

**Comment by scls19fr** [comment]
I'm wondering which aircraft do you use. I have Schempp-Hirth Discus-2c installed in my community folder but couldn't find it in Aircraft list in Sky Dolly when selecting File / Import / IGC

**Comment by till213** [comment]
Sky Dolly does not actually scan your Community folder ;) So in order to have an aircraft selectable in the dropdown list (of the import dialog) you have to record at least one (dummy) flight with it.

Or in other words: the already selectable aircraft are "pre-installed" in each "logbook" (database), as a courtesy of the developer (me ;)). Any additional aircraft is added ("upsert") as soon as it is recorded.

Does that help?

**Comment by scls19fr** [comment]
Thanks. I will record a flight with this glider.

**Comment by till213** [comment]
By the way:

https://github.com/till213/SkyDolly/blob/feature-iep/CHANGELOG.md

;)

Note that this is still a feature branch"iep" (= "import/export plugins") for the upcoming v0.9 - no date yet set ;)

P.S. If you happen to be some real-world glider pilot - or are otherwise attached to some aviation friends / clubs - please feel free to make some noise for Sky Dolly ;)

**Comment by till213** [comment]
A new IGC export plugin has just been merged into the current MAIN branch (for the upcoming 0.9 release - no release date set).

Both the IGC import and export plugin will received some more minor features (keyword: environmental noise level -> engine start/stop) and fine-tuning, but are both functional at this point.

If you want to test those features you can build Sky Dolly MAIN branch, as described in the BUILD.md instructions.

I will hence close this issue for now.
