### ISSUE TITLE
App reacts very slow if no connection to FS2020

### ISSUE THREAD

**Issue by jaber70599** [till213/SkyDolly#161]
**Describe the bug**
App reacts very slow if no connection to FS2020.

**To Reproduce**
1. Do NOT start FS2020
2. Start Skydolly
3. App opens very slow, approx. 30 secs 
4. Click on Menu -> File
5. App opens "File Drop down" with delay, approx 30 secs
6. Scroll down to Menu-> File -> Quit. Click Quit
7. Message form Windows operating systems pops up: "App does not react" 

**Expected behavior**
Normal response time to user input

**Screenshots**
N/A

**Application version:**
 - Version 017.2

**Additional context**

**Comment by till213** [comment]
Hello DocDressler :)

"Version 017.2" - this is not the latest version. The latest version is v0.17.5 which fixes the exact _regression_ that has been introduced with the v0.17.1 (the v0.17.0 is still working correct), namely that a network (IPv4) connection attempt was made instead of a "local" ("pipe") connection (due to an "off by one" application setting).

Network connections have a longer timeout (in the order of seconds, perhaps up to 30 seconds), and since Sky Dolly is not multithreaded (yet) such a connection attempt blocks the main (GUI) thread - hence the sluggish behaviour.

Also note that connection attempts are made every N seconds, where N is increasing as a [Fibonacci sequence ](https://en.wikipedia.org/wiki/Fibonacci_sequence)(0, 1, 1, 2, 3, 5, 8, ... - because why not).

-> **Update to the latest v0.17.5** and the connection issue should be solved: a "pipe" connection is made again (which times out much faster, essentially instantly) - unless you change the Sky Dolly application settings to an IPv4 or IPv6 network connection type (this is useful when running Sky Dolly and MSFS on _different_ Windows PCs - but then you actually need to manually edit the provided SimConnect.cfg client configuration and add the proper IP addresses, as documented in that file - found in the Sky Dolly application folder).

Also refer to the announcement on [flightsim.to](https://flightsim.to/file/9067/sky-dolly) and the [CHANGELOG](https://github.com/till213/SkyDolly/blob/main/CHANGELOG.md) for more details (and no, the v0.18.0 has not yet been released - but you get a glimpse on what's coming ;)).

**Comment by till213** [comment]
Solved in the latest v0.17.5 release.
