### ISSUE TITLE
Some KML tracks can't be imported

### ISSUE THREAD

**Issue by scls19fr** [till213/SkyDolly#17]
Hello,

Here is 2 kind of KML files which can't be imported
https://gist.github.com/scls19fr/d2746bf7491532793766845d3b42b0d8
https://gist.github.com/scls19fr/20c35cd2618c3ac63d15d4ba5dcad07d

that's the reason why I think GPX import #16 should also be considered because KML file can have very different variants.

Kind regards

**Comment by till213** [comment]
I am literally working on improving the existing KML import right now, too.

Also refer to the following ad-hoc documentation which I just added to a feature branch:

https://github.com/till213/SkyDolly/tree/feature-iep/src/Plugin/src/Import/KMLImport/doc

"KML file can have very different variants." - and yes, that's exactly the reason why most KML flavours out there cannot be read. In fact, Sky Dolly currently only parses KLM files from flightaware.com. In fact, Sky Dolly cannot even parse its _own_ exported KML files (as they do not contain any timestamps - just a "raw line segment").

But I do have intentions to improve both the KLM import (-> flightradar24.com) and export (maybe "color-coded" waypoints, according to altitude, velocity, acceleration etc.) plugins.

**Comment by scls19fr** [comment]
My opinion is that KML is more a rendering format that a GPS data format. So IGC and GPX are probably formats which should be prefered. On KML file came from Skydreamsoft SDVFR and the other one from Dual Skypro XGPS 160 GPS logger

**Comment by till213** [comment]
"My opinion is that KML is more a rendering format that a GPS data format."

Yes, I absolutely share this opinion. The initial motivation for the KML import plugin was also more to be able to import flights from flightaware.com (they provide access to current flight data as KML for free) than to have a fully blown and generic KML capable parser.

At least flightradar24.com also provides CSV data, but CSV data (and KML) is only available to their paying customers.

Anyway, that was the motivation for the KLM import plugin, because you are absolutely correct: KML can store "path data" in different elements (as outlined in my ad-hoc document linked above), and especially also flightradar24.com KML data adds additional flight data (such as speed and heading) in embedded HTML descriptions ;) In fact, they have the flight twice in the KLM, once as <Point> waypoints and a second time as (colour-encoded) <LineString>.

So one has to know exactly the nodes from which to extract the desired data (and dare you if that node hierarchy changes significantly ;))

**Comment by till213** [comment]
The KML import plugin now supports two new KLM flavours:

- KML from flightradar24.com
- Generic KML (gx:Track)

![grafik](https://user-images.githubusercontent.com/1205514/154861486-eb7a7e7c-ae69-4019-8ade-6c1bbdbbcb3c.png)

The latest generic KML parser has been integrated on a feature branch and will be merged into main in the foreseeable future (after some polishing and more testing with different KML files.

But it is already able to import one of the above KML files:

https://gist.github.com/scls19fr/d2746bf7491532793766845d3b42b0d8

(the other won't be supported, for the discussed reasons above).

I will hence close this issue for now.
