### ISSUE TITLE
Persistent Logbook

### ISSUE THREAD

**Issue by fsx-rwt** [till213/SkyDolly#75]
I tried to reply to your response on Flightsim.to private message board, but for some reason the reply seems to be sent to the BitBucket and never appear in the conversation stream.  So here is my reply:

=================================================================
Thanks for the quick and detailed response to my questions.  By copy I meant a recorded instructor flight that I would distribute with my flight training package.  

As you described the user could use the formation module to replay the flight while he is trying to follow it with his own aircraft. at the same time he would have the choice to record his own flight.

Based on your feedback I believe SkyDolly meets more than 95% of my need.  So for my next update, sometime in February, I am planning to distribute some instructor flights, recorded using your tool, provide a link to SKyDolly on Flightsim.To, and recommend to use it to foresee what they need to do in the training, and optionally fly with the instructor using the formation flight module.

As for the potential extension as a Logbook,  MSFS is really lacking in that respect, their logbook is currently useless and I don't see any free Logbook addon available other than using LittleNavMap for that purpose. 

If you ever think of filling the gap, you already have the base with SkyDolly.  If I could suggest an extension I would go with an extra table with:
⦁	Flight Number
⦁	Flight Title (Description)
⦁	Aircraft Type
⦁	Departure Date and Time
⦁	Departure Airport/Airborne location
⦁	Arrival Date and Time
⦁	Arrival Airport/Airborne location
⦁	Score (0 to 5 stars) or (0 to 100%)
⦁	Comments on the flights

If the user delete the flight recording, he should have the option to keep the flight Log portion.  Just some ideas but I am sure you can do better.  Anyway I can easily live with the current implementation and personally for the time being I will record all my training flights. to keep a record of my training.

Thanks again for a superb Job well done!!
=======================================================================

**Comment by till213** [comment]
Hello,

Thank you for all your suggestions, very much appreciated! And no, I indeed did not get any further reply via flightsim.to messages - I guess its "beta" label is there for a reason ;)

"As you described the user could use the formation module to replay the flight while he is trying to follow it with his own aircraft. at the same time he would have the choice to record his own flight."

That's correct: you can simply "follow" an existing formation flight (which is anything from up to and including one recorded aircraft), or keep on adding new aircraft to an existing flight (recording them).

With the known issues that "AI aircraft" are "jittering", especially with higher velocities and coming closer to your user aircraft. I try to address this "jitter" in an upcoming update.

 "If I could suggest an extension I would go with an extra table with:
⦁ Flight Number
⦁ Flight Title (Description)
⦁ Aircraft Type
* ..."

Note that most of those flight variables are already being recorded ;) They are simply not shown in the Sky Dolly logbook: I tried to keep that table deliberately as lean as possible. However you can already see most (if not all) your mentioned variables in the "Flight" dialog (including user-editable comments), simply press key **F** (or activate the dialog via menu). 

While you cannot currently filter the logbook with all those recorded variables I might add more logbook filters in the future, including a "star rating" (1-5 stars, as given by the user).

"I am planning to distribute some instructor flights, recorded using your tool"

Sounds great :) Note that currently your best option to exchange your recorded flights with others is the CSV (comma-separated values) format, specifically of course the "Sky Dolly" flavour (a dropdown box in the export dialog lets you choose the CSV "flavour").

However due to the nature of the CSV format - each row is supposed to contain the same number of data "columns" - that format is not very suited to exchange recorded flights (aircraft) with 100% accuracy, e.g. all "Flight" specific variables (flight conditions, comments etc.) are "lost" (not exported).

I plan to implement a full "logbook export" - essentially in the exact same SQL database format as the logbook itself", but that is for later (well, I couldn't resist already creating a corresponding "feature branch" and start with some initial coding ;)). But no timeline promise made here ;)

**Comment by fsx-rwt** [comment]
For distribution I was thinking of providing the SQlite database of recorded flight itself with a link to SkyDolly on Fliightsim.to for them to download.  You can then keep track of who is downloading your tool.  They could then open the existing database and continue to populate it.

I will ;keep you posted.

**Comment by till213** [comment]
„ For distribution I was thinking of providing the SQlite database of recorded flight itself“

This is of course also a possibility ;)

Again, I intend to implement import/export plugins with the „Sky Dolly SQL format“, such that it will be possible to export the selected aircraft (only) - „multi-selection“ of flights in the logbook (for export) is also on my to-do list.

I will keep this issue open and use it for the mentioned import/export plugins.

**Comment by till213** [comment]
The new Sky Dolly logbook (*.sdlog) import and export plugins will be part of the upcoming Sky Dolly v0.16 release.
