### ISSUE TITLE
Lights don't work on AI aircraft

### ISSUE THREAD

**Issue by scondas** [till213/SkyDolly#88]
I am using 0.15.0 and I do not see the lights I requested on formation aircraft.  My test case is A320 as both the user aircraft and AI formation aircraft.  The lights turn back on if I make a formation aircraft my user aircraft.  Thanks for investigating.

**Comment by till213** [comment]
There is probably not much to investigate: most simulation variables are in fact simply "ignored" by AI aircraft. In fact, I am sending the light data as "bitfield" to AI aircraft (and since 0.14 "events" to the "user aircraft"). But whether the AI aircraft is reacting to this "simulation variable" is out of my control.

I will keep this open and verify - but again, don't hold your breath ;)

**Comment by scondas** [comment]
I have found other MSFS models for which the lights do work, so I concur this is not a Sky Dolly issue.  Closing this bug.

**Comment by till213** [comment]
Just as a timely coincidence, I just stumbled over:

https://devsupport.flightsimulator.com/questions/14494/no-external-lighting-on-simconnect-aicreatenonatca.html

There seem to be indeed some (third-party) AI aircraft that are "left in the dark", specifically when created with SimConnect_AICreateNonATCAircraft. That happens to be the exact same SimConnnect API function that Sky Dolly calls as well when creating AI aircraft (-> "formation flight").

This function spawns an "AI aircraft", but one that is "not controlled by ATC" (that is, one that doesn't follow a pre-defined flight plan), but instead "controlled by whatever means" (= by the "application").

So there seems indeed to be an issue with "non-ATC AI aircraft and lights" - at least for some aircraft.
